name: "trigger-github-pages"
description: "Configure GitHub Pages and trigger deployment"
author: "Jérémie Lumbroso <lumbroso@cs.princeton.edu>"

inputs:
  branch:
    description: "Repository branch to publish the GitHub Pages to."
    default: "gh-pages"
    required: false

  path:
    description: "Path to publish the GitHub Pages from."
    default: "/"
    required: false

  github_token:
    description: "GitHub token to deploy (because Actions can't access directly)."
    required: true

  homepage:
    description: "URL to which to set the repository homepage (optional)."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Trigger deployment of GitHub Pages
      shell: bash
      run: |
        set -e
        sudo apt-get install -y curl
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.repository_owner }}:${{ inputs.github_token }}" "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pages" -d '{"source":{"branch":"${{ inputs.branch }}","path":"${{ inputs.path }}"}}'
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.github_token }}" "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pages" -d '{"source":{"branch":"${{ inputs.branch }}","path":"${{ inputs.path }}"}}'

    - name: Set repository homepage
      shell: bash
      run: |
        if [ ! -z "${{ inputs.homepage }}" ]
        then
          curl -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.github_token }}" "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}" -d '{"homepage":"${{ inputs.homepage }}"}'
        fi
