name: "deploy-github-pages"
description: "Build the Hugo website and deploy to GitHub Pages"
author: Jérémie Lumbroso

inputs:
  branch:
    description: "Repository branch to publish the GitHub Pages to."
    default: "gh-pages"
    required: false

  checkout:
    description: "Determines whether we checkout the repository before proceeding."
    default: "true"
    required: false

  github_token:
    description: "GitHub token to deploy (because Actions can't access directly)."
    required: true

  publish_directory:
    description: "Directory from which to build and publish the Hugo website."
    default: "./"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      if: ${{ github.event.inputs.checkout == 'true' }}
      with:
        submodules: true # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Node.js to build theme
      uses: actions/setup-node@v1
      with:
        # pin node.js version
        node-version: "17.6.0"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.5.0
      with:
        # pin hugo version
        hugo-version: "0.101.0"
        extended: true

    - name: Install and build Javascript part of site
      working-directory: "${{ inputs.publish_directory }}"
      shell: bash
      run: |
        set -e
        tree -a
        ( [ -f "package.json" ] && npm install ) || echo "no npm install needed"

    - name: Build site with Hugo
      working-directory: "${{ inputs.publish_directory }}"
      shell: bash
      run: |
        hugo mod npm pack
        hugo --minify

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: "${{ inputs.github_token }}"
        publish_branch: "${{ inputs.branch }}"
        publish_dir: "${{ inputs.publish_directory }}/public"
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"

    # - name: Push branch to GitHub Pages
    #   working-directory: "${{ inputs.publish_directory }}"
    #   shell: bash
    #   run: |
    #     set -e
    #     sudo apt-get install -y curl
    #     curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.github_token }}" "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pages" -d '{"source":{"branch":"gh-pages","path":"/"}}'
